name: valor-pro-build-action
description: docker build and push action.
author: valor-pro 
branding:
  icon: 'thumbs-up'
  color: 'white'

inputs:
  username:
    description: 'Username used to log against the Docker registry'
    required: true
  password:
    description: 'Password or personal access token used to log against the Docker registry'
    required: true
  host:
    description: 'Docker registry host'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        pwd
        ls -lha

        env | grep -v ^GITHUB | sort
        if  [ -f .env ]; then
            export $(grep -v '^#' .env  | xargs)
        fi
        set -x 
        REPO_NAME=${{ github.event.repository.name }}
        IMAGE_TAG=$(date +%Y%m%d%H%M%S)
        IMAGE_NAME=$hostREPO_NAME:IMAGE_TAG 
        echo "docker build . -t $IMAGE_NAME" | sed 's/./& /g'
        echo "docker login -u docker login -u $USERNAME -p $PASSWORD $HOST" | sed 's/./& /g'
        docker build . -t IMAGE_NAME
        docker login -u $USERNAME -p $PASSWORD $HOST
        docker push IMAGE_NAME
      shell: bash
      env:
        USERNAME: "${{ inputs.username }}"
        PASSWORD: "${{ inputs.password }}"
        HOST: "${{ inputs.host }}"

